# npm install
# npm run build
# <upload to s3>

language: ruby
rvm:
- 2.5.1

install:
- bundle install
- nvm install stable && nvm alias default stable
- npm install npm@latest -g
- npm --version
- npm install

script:
- bundle exec rake spec
- npm run test