language: ruby
cache:
  bundler: true
  directories:
  - node_modules # NPM packages
rvm:
- 2.5.1

install:
- bundle install
- nvm install stable && nvm alias default stable
- npm install npm@latest -g
- npm --version

script:
- cd client
- npm install
- CI=true npm run test
- npm run build

deploy:
  provider: s3
  access_key_id: AKIAIVRL56ULYU5DO7MA
  secret_access_key:
    secure: nUhl84igvBJJ5HvMew96xqxnf7R2aO6AP3Pu5SbuV1QbB4FgWsHYw1Lf7f350BESfntwU3b/0YufUsyQgev2wvAokXHJR+10PhkH7gEn/NmLGEQUJ5hndz+xhhWEk6DwfvnSxpXmZOD30tdT14HZNIvqIgJmKcj4soiGkYSATQvnJULl5LoD9zsHKEyGKKyBM0TRjJpBSz83K2atTge4b0TatmEDSXMaHE2Ec29WX5VJd6TyRcyMPOp1+RlK3ei+RQEfngtqqC6t7fpJM6Yq28Aiw1CMAmXVltU0g1ssIzd/1nyldTqqRpf6odJbn4Z46bWMa1/RlaWjZjdfwP448ItV8Qa6Rh2uHmT0pI1iDeCUaWtIHagYw4+FMTN69aBakru39OyxRZjnxmTlWNMt0iXGdX2okEYK36GoHateJwwRkDyrd2bXcWcrb71mOVt3YZzbNZmSpOw2OxNPh5F+D4kGjsOrV3lHPaWMgkTw3hYzqwwLhcRxDoFaNwCnMI0z4XsVHznZS5d0Ki0s4IzQN1wRIYNTMB1fJ9PlOelHykMqKFydcQRYqIO9DwV03howYIo1F27ZHBwnJ4G1NK6qefzhCXGpHEcpFhUcbEt0aZccCUbpL/PcTSgM8IrFPX957MZe8zvcjCblE5jJb8o2R0JJutoybB0nnqzH9Iu7H4I=
  bucket: "yarrble.com"
  local-dir: build
  acl: public_read
  on:
    repo: squirrelnest/yarrble
